//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Btob.PortailWeb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PortailWeb_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb")]
    public partial class PortailWeb : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ExportAvoirLineOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExportAvoirOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExportInvoiceLineOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExportInvoiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExportItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExportOrderHeaderOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExportOrderLineOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExportPictureToBase64OperationCompleted;
        
        private System.Threading.SendOrPostCallback ExportShipementLineOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExportShipmentHeaderOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReportToPDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PortailWeb() {
            this.Url = global::Btob.Properties.Settings.Default.Btob_PortailWeb_PortailWeb;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ExportAvoirLineCompletedEventHandler ExportAvoirLineCompleted;
        
        /// <remarks/>
        public event ExportAvoirCompletedEventHandler ExportAvoirCompleted;
        
        /// <remarks/>
        public event ExportInvoiceLineCompletedEventHandler ExportInvoiceLineCompleted;
        
        /// <remarks/>
        public event ExportInvoiceCompletedEventHandler ExportInvoiceCompleted;
        
        /// <remarks/>
        public event ExportItemsCompletedEventHandler ExportItemsCompleted;
        
        /// <remarks/>
        public event ExportOrderHeaderCompletedEventHandler ExportOrderHeaderCompleted;
        
        /// <remarks/>
        public event ExportOrderLineCompletedEventHandler ExportOrderLineCompleted;
        
        /// <remarks/>
        public event ExportPictureToBase64CompletedEventHandler ExportPictureToBase64Completed;
        
        /// <remarks/>
        public event ExportShipementLineCompletedEventHandler ExportShipementLineCompleted;
        
        /// <remarks/>
        public event ExportShipmentHeaderCompletedEventHandler ExportShipmentHeaderCompleted;
        
        /// <remarks/>
        public event ReportToPDFCompletedEventHandler ReportToPDFCompleted;
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortailWeb:ExportAvoirLine", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", ResponseElementName="ExportAvoirLine_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExportAvoirLine(ref SalesCrMemoLines avoirLines, string orderFilter) {
            object[] results = this.Invoke("ExportAvoirLine", new object[] {
                        avoirLines,
                        orderFilter});
            avoirLines = ((SalesCrMemoLines)(results[0]));
        }
        
        /// <remarks/>
        public void ExportAvoirLineAsync(SalesCrMemoLines avoirLines, string orderFilter) {
            this.ExportAvoirLineAsync(avoirLines, orderFilter, null);
        }
        
        /// <remarks/>
        public void ExportAvoirLineAsync(SalesCrMemoLines avoirLines, string orderFilter, object userState) {
            if ((this.ExportAvoirLineOperationCompleted == null)) {
                this.ExportAvoirLineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportAvoirLineOperationCompleted);
            }
            this.InvokeAsync("ExportAvoirLine", new object[] {
                        avoirLines,
                        orderFilter}, this.ExportAvoirLineOperationCompleted, userState);
        }
        
        private void OnExportAvoirLineOperationCompleted(object arg) {
            if ((this.ExportAvoirLineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportAvoirLineCompleted(this, new ExportAvoirLineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortailWeb:ExportAvoir", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", ResponseElementName="ExportAvoir_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExportAvoir(ref SalesCrMemoHeaders avoir, string custFilter, string avr) {
            object[] results = this.Invoke("ExportAvoir", new object[] {
                        avoir,
                        custFilter,
                        avr});
            avoir = ((SalesCrMemoHeaders)(results[0]));
        }
        
        /// <remarks/>
        public void ExportAvoirAsync(SalesCrMemoHeaders avoir, string custFilter, string avr) {
            this.ExportAvoirAsync(avoir, custFilter, avr, null);
        }
        
        /// <remarks/>
        public void ExportAvoirAsync(SalesCrMemoHeaders avoir, string custFilter, string avr, object userState) {
            if ((this.ExportAvoirOperationCompleted == null)) {
                this.ExportAvoirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportAvoirOperationCompleted);
            }
            this.InvokeAsync("ExportAvoir", new object[] {
                        avoir,
                        custFilter,
                        avr}, this.ExportAvoirOperationCompleted, userState);
        }
        
        private void OnExportAvoirOperationCompleted(object arg) {
            if ((this.ExportAvoirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportAvoirCompleted(this, new ExportAvoirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortailWeb:ExportInvoiceLine", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", ResponseElementName="ExportInvoiceLine_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExportInvoiceLine(ref SalesInvoiceLines invoiceLines, string orderFilter) {
            object[] results = this.Invoke("ExportInvoiceLine", new object[] {
                        invoiceLines,
                        orderFilter});
            invoiceLines = ((SalesInvoiceLines)(results[0]));
        }
        
        /// <remarks/>
        public void ExportInvoiceLineAsync(SalesInvoiceLines invoiceLines, string orderFilter) {
            this.ExportInvoiceLineAsync(invoiceLines, orderFilter, null);
        }
        
        /// <remarks/>
        public void ExportInvoiceLineAsync(SalesInvoiceLines invoiceLines, string orderFilter, object userState) {
            if ((this.ExportInvoiceLineOperationCompleted == null)) {
                this.ExportInvoiceLineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportInvoiceLineOperationCompleted);
            }
            this.InvokeAsync("ExportInvoiceLine", new object[] {
                        invoiceLines,
                        orderFilter}, this.ExportInvoiceLineOperationCompleted, userState);
        }
        
        private void OnExportInvoiceLineOperationCompleted(object arg) {
            if ((this.ExportInvoiceLineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportInvoiceLineCompleted(this, new ExportInvoiceLineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortailWeb:ExportInvoice", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", ResponseElementName="ExportInvoice_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExportInvoice(ref SalesInvoiceHeaders invoice, string custFilter, string inv) {
            object[] results = this.Invoke("ExportInvoice", new object[] {
                        invoice,
                        custFilter,
                        inv});
            invoice = ((SalesInvoiceHeaders)(results[0]));
        }
        
        /// <remarks/>
        public void ExportInvoiceAsync(SalesInvoiceHeaders invoice, string custFilter, string inv) {
            this.ExportInvoiceAsync(invoice, custFilter, inv, null);
        }
        
        /// <remarks/>
        public void ExportInvoiceAsync(SalesInvoiceHeaders invoice, string custFilter, string inv, object userState) {
            if ((this.ExportInvoiceOperationCompleted == null)) {
                this.ExportInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportInvoiceOperationCompleted);
            }
            this.InvokeAsync("ExportInvoice", new object[] {
                        invoice,
                        custFilter,
                        inv}, this.ExportInvoiceOperationCompleted, userState);
        }
        
        private void OnExportInvoiceOperationCompleted(object arg) {
            if ((this.ExportInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportInvoiceCompleted(this, new ExportInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortailWeb:ExportItems", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", ResponseElementName="ExportItems_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExportItems(string desc, ref string varJSON) {
            object[] results = this.Invoke("ExportItems", new object[] {
                        desc,
                        varJSON});
            varJSON = ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ExportItemsAsync(string desc, string varJSON) {
            this.ExportItemsAsync(desc, varJSON, null);
        }
        
        /// <remarks/>
        public void ExportItemsAsync(string desc, string varJSON, object userState) {
            if ((this.ExportItemsOperationCompleted == null)) {
                this.ExportItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportItemsOperationCompleted);
            }
            this.InvokeAsync("ExportItems", new object[] {
                        desc,
                        varJSON}, this.ExportItemsOperationCompleted, userState);
        }
        
        private void OnExportItemsOperationCompleted(object arg) {
            if ((this.ExportItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportItemsCompleted(this, new ExportItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortailWeb:ExportOrderHeader", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", ResponseElementName="ExportOrderHeader_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExportOrderHeader(ref SalesHeaders orderHeader, string custFilter, string itemFilter) {
            object[] results = this.Invoke("ExportOrderHeader", new object[] {
                        orderHeader,
                        custFilter,
                        itemFilter});
            orderHeader = ((SalesHeaders)(results[0]));
        }
        
        /// <remarks/>
        public void ExportOrderHeaderAsync(SalesHeaders orderHeader, string custFilter, string itemFilter) {
            this.ExportOrderHeaderAsync(orderHeader, custFilter, itemFilter, null);
        }
        
        /// <remarks/>
        public void ExportOrderHeaderAsync(SalesHeaders orderHeader, string custFilter, string itemFilter, object userState) {
            if ((this.ExportOrderHeaderOperationCompleted == null)) {
                this.ExportOrderHeaderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportOrderHeaderOperationCompleted);
            }
            this.InvokeAsync("ExportOrderHeader", new object[] {
                        orderHeader,
                        custFilter,
                        itemFilter}, this.ExportOrderHeaderOperationCompleted, userState);
        }
        
        private void OnExportOrderHeaderOperationCompleted(object arg) {
            if ((this.ExportOrderHeaderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportOrderHeaderCompleted(this, new ExportOrderHeaderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortailWeb:ExportOrderLine", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", ResponseElementName="ExportOrderLine_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExportOrderLine(ref SalesLines orderLines, string orderFilter) {
            object[] results = this.Invoke("ExportOrderLine", new object[] {
                        orderLines,
                        orderFilter});
            orderLines = ((SalesLines)(results[0]));
        }
        
        /// <remarks/>
        public void ExportOrderLineAsync(SalesLines orderLines, string orderFilter) {
            this.ExportOrderLineAsync(orderLines, orderFilter, null);
        }
        
        /// <remarks/>
        public void ExportOrderLineAsync(SalesLines orderLines, string orderFilter, object userState) {
            if ((this.ExportOrderLineOperationCompleted == null)) {
                this.ExportOrderLineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportOrderLineOperationCompleted);
            }
            this.InvokeAsync("ExportOrderLine", new object[] {
                        orderLines,
                        orderFilter}, this.ExportOrderLineOperationCompleted, userState);
        }
        
        private void OnExportOrderLineOperationCompleted(object arg) {
            if ((this.ExportOrderLineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportOrderLineCompleted(this, new ExportOrderLineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortailWeb:ExportPictureToBase64", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", ResponseElementName="ExportPictureToBase64_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExportPictureToBase64(ref string iMG, string itemNo) {
            object[] results = this.Invoke("ExportPictureToBase64", new object[] {
                        iMG,
                        itemNo});
            iMG = ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ExportPictureToBase64Async(string iMG, string itemNo) {
            this.ExportPictureToBase64Async(iMG, itemNo, null);
        }
        
        /// <remarks/>
        public void ExportPictureToBase64Async(string iMG, string itemNo, object userState) {
            if ((this.ExportPictureToBase64OperationCompleted == null)) {
                this.ExportPictureToBase64OperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportPictureToBase64OperationCompleted);
            }
            this.InvokeAsync("ExportPictureToBase64", new object[] {
                        iMG,
                        itemNo}, this.ExportPictureToBase64OperationCompleted, userState);
        }
        
        private void OnExportPictureToBase64OperationCompleted(object arg) {
            if ((this.ExportPictureToBase64Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportPictureToBase64Completed(this, new ExportPictureToBase64CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortailWeb:ExportShipementLine", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", ResponseElementName="ExportShipementLine_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExportShipementLine(ref SalesShipementLines shipementLines, string orderFilter) {
            object[] results = this.Invoke("ExportShipementLine", new object[] {
                        shipementLines,
                        orderFilter});
            shipementLines = ((SalesShipementLines)(results[0]));
        }
        
        /// <remarks/>
        public void ExportShipementLineAsync(SalesShipementLines shipementLines, string orderFilter) {
            this.ExportShipementLineAsync(shipementLines, orderFilter, null);
        }
        
        /// <remarks/>
        public void ExportShipementLineAsync(SalesShipementLines shipementLines, string orderFilter, object userState) {
            if ((this.ExportShipementLineOperationCompleted == null)) {
                this.ExportShipementLineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportShipementLineOperationCompleted);
            }
            this.InvokeAsync("ExportShipementLine", new object[] {
                        shipementLines,
                        orderFilter}, this.ExportShipementLineOperationCompleted, userState);
        }
        
        private void OnExportShipementLineOperationCompleted(object arg) {
            if ((this.ExportShipementLineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportShipementLineCompleted(this, new ExportShipementLineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortailWeb:ExportShipmentHeader", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", ResponseElementName="ExportShipmentHeader_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExportShipmentHeader(ref SalesShipmentHeaders shipmentList, string custFilter, string itemFilter) {
            object[] results = this.Invoke("ExportShipmentHeader", new object[] {
                        shipmentList,
                        custFilter,
                        itemFilter});
            shipmentList = ((SalesShipmentHeaders)(results[0]));
        }
        
        /// <remarks/>
        public void ExportShipmentHeaderAsync(SalesShipmentHeaders shipmentList, string custFilter, string itemFilter) {
            this.ExportShipmentHeaderAsync(shipmentList, custFilter, itemFilter, null);
        }
        
        /// <remarks/>
        public void ExportShipmentHeaderAsync(SalesShipmentHeaders shipmentList, string custFilter, string itemFilter, object userState) {
            if ((this.ExportShipmentHeaderOperationCompleted == null)) {
                this.ExportShipmentHeaderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportShipmentHeaderOperationCompleted);
            }
            this.InvokeAsync("ExportShipmentHeader", new object[] {
                        shipmentList,
                        custFilter,
                        itemFilter}, this.ExportShipmentHeaderOperationCompleted, userState);
        }
        
        private void OnExportShipmentHeaderOperationCompleted(object arg) {
            if ((this.ExportShipmentHeaderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportShipmentHeaderCompleted(this, new ExportShipmentHeaderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortailWeb:ReportToPDF", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", ResponseElementName="ReportToPDF_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ReportToPDF(ref string pDF, ref bool executed, int idReport, string document) {
            object[] results = this.Invoke("ReportToPDF", new object[] {
                        pDF,
                        executed,
                        idReport,
                        document});
            pDF = ((string)(results[0]));
            executed = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void ReportToPDFAsync(string pDF, bool executed, int idReport, string document) {
            this.ReportToPDFAsync(pDF, executed, idReport, document, null);
        }
        
        /// <remarks/>
        public void ReportToPDFAsync(string pDF, bool executed, int idReport, string document, object userState) {
            if ((this.ReportToPDFOperationCompleted == null)) {
                this.ReportToPDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReportToPDFOperationCompleted);
            }
            this.InvokeAsync("ReportToPDF", new object[] {
                        pDF,
                        executed,
                        idReport,
                        document}, this.ReportToPDFOperationCompleted, userState);
        }
        
        private void OnReportToPDFOperationCompleted(object arg) {
            if ((this.ReportToPDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReportToPDFCompleted(this, new ReportToPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PortailWeb:login", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", ResponseElementName="login_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PortailWeb", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool login(string user, string pwd, ref string customerNo, ref string description, ref decimal solde) {
            object[] results = this.Invoke("login", new object[] {
                        user,
                        pwd,
                        customerNo,
                        description,
                        solde});
            customerNo = ((string)(results[1]));
            description = ((string)(results[2]));
            solde = ((decimal)(results[3]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string user, string pwd, string customerNo, string description, decimal solde) {
            this.loginAsync(user, pwd, customerNo, description, solde, null);
        }
        
        /// <remarks/>
        public void loginAsync(string user, string pwd, string customerNo, string description, decimal solde, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        user,
                        pwd,
                        customerNo,
                        description,
                        solde}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50107")]
    public partial class SalesCrMemoLines {
        
        private SalesCrMemoLine[] salesCrMemoLineField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesCrMemoLine")]
        public SalesCrMemoLine[] SalesCrMemoLine {
            get {
                return this.salesCrMemoLineField;
            }
            set {
                this.salesCrMemoLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50107")]
    public partial class SalesCrMemoLine {
        
        private string noField;
        
        private string descriptionField;
        
        private decimal quantityField;
        
        private decimal amountField;
        
        private decimal amountIncludingVATField;
        
        public SalesCrMemoLine() {
            this.quantityField = ((decimal)(0m));
            this.amountField = ((decimal)(0m));
            this.amountIncludingVATField = ((decimal)(0m));
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public decimal AmountIncludingVAT {
            get {
                return this.amountIncludingVATField;
            }
            set {
                this.amountIncludingVATField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50102")]
    public partial class SalesShipmentHeader {
        
        private string noField;
        
        private string selltoCustomerNoField;
        
        private string selltoCustomerNameField;
        
        private System.DateTime postingDateField;
        
        public SalesShipmentHeader() {
            this.postingDateField = new System.DateTime(0);
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string SelltoCustomerNo {
            get {
                return this.selltoCustomerNoField;
            }
            set {
                this.selltoCustomerNoField = value;
            }
        }
        
        /// <remarks/>
        public string SelltoCustomerName {
            get {
                return this.selltoCustomerNameField;
            }
            set {
                this.selltoCustomerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PostingDate {
            get {
                return this.postingDateField;
            }
            set {
                this.postingDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50102")]
    public partial class SalesShipmentHeaders {
        
        private SalesShipmentHeader[] salesShipmentHeaderField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesShipmentHeader")]
        public SalesShipmentHeader[] SalesShipmentHeader {
            get {
                return this.salesShipmentHeaderField;
            }
            set {
                this.salesShipmentHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50103")]
    public partial class SalesShipmentLine {
        
        private string noField;
        
        private string descriptionField;
        
        private decimal quantityField;
        
        public SalesShipmentLine() {
            this.quantityField = ((decimal)(0m));
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50103")]
    public partial class SalesShipementLines {
        
        private SalesShipmentLine[] salesShipmentLineField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesShipmentLine")]
        public SalesShipmentLine[] SalesShipmentLine {
            get {
                return this.salesShipmentLineField;
            }
            set {
                this.salesShipmentLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50101")]
    public partial class SalesLine {
        
        private string noField;
        
        private string descriptionField;
        
        private decimal quantityField;
        
        private decimal unitPriceField;
        
        private decimal amountField;
        
        private decimal amountIncludingVATField;
        
        public SalesLine() {
            this.quantityField = ((decimal)(0m));
            this.unitPriceField = ((decimal)(0m));
            this.amountField = ((decimal)(0m));
            this.amountIncludingVATField = ((decimal)(0m));
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public decimal UnitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public decimal AmountIncludingVAT {
            get {
                return this.amountIncludingVATField;
            }
            set {
                this.amountIncludingVATField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50101")]
    public partial class SalesLines {
        
        private SalesLine[] salesLineField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesLine")]
        public SalesLine[] SalesLine {
            get {
                return this.salesLineField;
            }
            set {
                this.salesLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50100")]
    public partial class SalesHeader {
        
        private string noField;
        
        private string selltoCustomerNoField;
        
        private string selltoCustomerNameField;
        
        private decimal amountField;
        
        private decimal amountIncludingVATField;
        
        private System.DateTime postingDateField;
        
        public SalesHeader() {
            this.amountField = ((decimal)(0m));
            this.amountIncludingVATField = ((decimal)(0m));
            this.postingDateField = new System.DateTime(0);
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string SelltoCustomerNo {
            get {
                return this.selltoCustomerNoField;
            }
            set {
                this.selltoCustomerNoField = value;
            }
        }
        
        /// <remarks/>
        public string SelltoCustomerName {
            get {
                return this.selltoCustomerNameField;
            }
            set {
                this.selltoCustomerNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public decimal AmountIncludingVAT {
            get {
                return this.amountIncludingVATField;
            }
            set {
                this.amountIncludingVATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PostingDate {
            get {
                return this.postingDateField;
            }
            set {
                this.postingDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50100")]
    public partial class SalesHeaders {
        
        private SalesHeader[] salesHeaderField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesHeader")]
        public SalesHeader[] SalesHeader {
            get {
                return this.salesHeaderField;
            }
            set {
                this.salesHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50104")]
    public partial class SalesInvoiceHeader {
        
        private string noField;
        
        private string selltoCustomerNoField;
        
        private string selltoCustomerNameField;
        
        private decimal amountField;
        
        private decimal amountIncludingVATField;
        
        private System.DateTime postingDateField;
        
        public SalesInvoiceHeader() {
            this.amountField = ((decimal)(0m));
            this.amountIncludingVATField = ((decimal)(0m));
            this.postingDateField = new System.DateTime(0);
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string SelltoCustomerNo {
            get {
                return this.selltoCustomerNoField;
            }
            set {
                this.selltoCustomerNoField = value;
            }
        }
        
        /// <remarks/>
        public string SelltoCustomerName {
            get {
                return this.selltoCustomerNameField;
            }
            set {
                this.selltoCustomerNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public decimal AmountIncludingVAT {
            get {
                return this.amountIncludingVATField;
            }
            set {
                this.amountIncludingVATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PostingDate {
            get {
                return this.postingDateField;
            }
            set {
                this.postingDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50104")]
    public partial class SalesInvoiceHeaders {
        
        private SalesInvoiceHeader[] salesInvoiceHeaderField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesInvoiceHeader")]
        public SalesInvoiceHeader[] SalesInvoiceHeader {
            get {
                return this.salesInvoiceHeaderField;
            }
            set {
                this.salesInvoiceHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50106")]
    public partial class SalesInvoiceLine {
        
        private string noField;
        
        private string descriptionField;
        
        private decimal quantityField;
        
        private decimal amountField;
        
        private decimal amountIncludingVATField;
        
        public SalesInvoiceLine() {
            this.quantityField = ((decimal)(0m));
            this.amountField = ((decimal)(0m));
            this.amountIncludingVATField = ((decimal)(0m));
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public decimal AmountIncludingVAT {
            get {
                return this.amountIncludingVATField;
            }
            set {
                this.amountIncludingVATField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50106")]
    public partial class SalesInvoiceLines {
        
        private SalesInvoiceLine[] salesInvoiceLineField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesInvoiceLine")]
        public SalesInvoiceLine[] SalesInvoiceLine {
            get {
                return this.salesInvoiceLineField;
            }
            set {
                this.salesInvoiceLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50105")]
    public partial class SalesCrMemoHeader {
        
        private string noField;
        
        private string selltoCustomerNoField;
        
        private string selltoCustomerNameField;
        
        private decimal amountField;
        
        private decimal amountIncludingVATField;
        
        private System.DateTime postingDateField;
        
        public SalesCrMemoHeader() {
            this.amountField = ((decimal)(0m));
            this.amountIncludingVATField = ((decimal)(0m));
            this.postingDateField = new System.DateTime(0);
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string SelltoCustomerNo {
            get {
                return this.selltoCustomerNoField;
            }
            set {
                this.selltoCustomerNoField = value;
            }
        }
        
        /// <remarks/>
        public string SelltoCustomerName {
            get {
                return this.selltoCustomerNameField;
            }
            set {
                this.selltoCustomerNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public decimal AmountIncludingVAT {
            get {
                return this.amountIncludingVATField;
            }
            set {
                this.amountIncludingVATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PostingDate {
            get {
                return this.postingDateField;
            }
            set {
                this.postingDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50105")]
    public partial class SalesCrMemoHeaders {
        
        private SalesCrMemoHeader[] salesCrMemoHeaderField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesCrMemoHeader")]
        public SalesCrMemoHeader[] SalesCrMemoHeader {
            get {
                return this.salesCrMemoHeaderField;
            }
            set {
                this.salesCrMemoHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ExportAvoirLineCompletedEventHandler(object sender, ExportAvoirLineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExportAvoirLineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExportAvoirLineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesCrMemoLines avoirLines {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesCrMemoLines)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ExportAvoirCompletedEventHandler(object sender, ExportAvoirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExportAvoirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExportAvoirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesCrMemoHeaders avoir {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesCrMemoHeaders)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ExportInvoiceLineCompletedEventHandler(object sender, ExportInvoiceLineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExportInvoiceLineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExportInvoiceLineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesInvoiceLines invoiceLines {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesInvoiceLines)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ExportInvoiceCompletedEventHandler(object sender, ExportInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExportInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExportInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesInvoiceHeaders invoice {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesInvoiceHeaders)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ExportItemsCompletedEventHandler(object sender, ExportItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExportItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExportItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string varJSON {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ExportOrderHeaderCompletedEventHandler(object sender, ExportOrderHeaderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExportOrderHeaderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExportOrderHeaderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesHeaders orderHeader {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesHeaders)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ExportOrderLineCompletedEventHandler(object sender, ExportOrderLineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExportOrderLineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExportOrderLineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesLines orderLines {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesLines)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ExportPictureToBase64CompletedEventHandler(object sender, ExportPictureToBase64CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExportPictureToBase64CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExportPictureToBase64CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string iMG {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ExportShipementLineCompletedEventHandler(object sender, ExportShipementLineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExportShipementLineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExportShipementLineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesShipementLines shipementLines {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesShipementLines)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ExportShipmentHeaderCompletedEventHandler(object sender, ExportShipmentHeaderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExportShipmentHeaderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExportShipmentHeaderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesShipmentHeaders shipmentList {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesShipmentHeaders)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ReportToPDFCompletedEventHandler(object sender, ReportToPDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReportToPDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReportToPDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string pDF {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool executed {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string customerNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public decimal solde {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[3]));
            }
        }
    }
}

#pragma warning restore 1591